name: Flo
favicon: null
layout_spectrum: 0.20341496937908232
typography_spectrum: 0.27450718032196164
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.0978377799037844
  lightness: 0.6162685919553041
  saturation: 0.8862112776841968
  rhythmicContrast: 0.7035265734884888
purpose: []
